apiVersion: v2
name: convoy
description: Open Source Webhooks Gateway
type: application
version: "2.4.1"
appVersion: "24.6.4"
keywords:
  - Webhooks
  - Kubernetes
  - Convoy
maintainers:
  - name: Convoy Engineering Team
    email: engineering@getconvoy.io
    url: https://getconvoy.io
dependencies:
  - name: postgresql
    version: 12.5.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.11.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
