{{- if and .Values.global.convoy.cacert_content (not .Values.global.convoy.cacert_secret_name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "convoy-server.fullname" . }}-cacert
  labels:
    app.kubernetes.io/name: {{ include "convoy-server.name" . }}
    helm.sh/chart: {{ include "convoy-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  ca.crt: {{ .Values.global.convoy.cacert_content | b64enc | quote }}
{{- end }} 