{{- if and (not .Values.global.convoy.jwt_secret_name) (or .Values.global.convoy.jwt_secret .Values.global.convoy.jwt_refresh_secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "convoy-server.fullname" . }}-jwt
  labels:
    app.kubernetes.io/name: {{ include "convoy-server.name" . }}
    helm.sh/chart: {{ include "convoy-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  jwt_secret: {{ .Values.global.convoy.jwt_secret | default (randAlphaNum 32) | b64enc | quote }}
  jwt_refresh_secret: {{ .Values.global.convoy.jwt_refresh_secret | default (randAlphaNum 32) | b64enc | quote }}
{{- end }} 