{{- if and (not .Values.global.convoy.license_key_secret_name) .Values.global.convoy.license_key }}
apiVersion: v1
kind: Secret
metadata:
  name: convoy-license-key
  labels:
    app.kubernetes.io/name: {{ include "convoy-agent.name" . }}
    helm.sh/chart: {{ include "convoy-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  license_key: {{ .Values.global.convoy.license_key | b64enc | quote }}
{{- end }}
