# Default values for convoy-stream.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enabled: true
app:
  replicaCount: 1
  port: 5008
  resources:
    limits:
      cpu: 50m
      memory: 60Mi
    requests:
      cpu: 40m
      memory: 50Mi
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "{{ .Values.app.port }}"

env:
  environment: ""
  tracer:
    enabled: true
    app_name: ""
    config_enabled: true
    distributed_tracer_enabled: true
    license_key: ""
    type: ""

image:
  repository: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy
  pullPolicy: Always
  tag: v23.05.3

nameOverride: "convoy-stream"
fullNameOverride: "convoy-stream"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: []
  ingressClassName: ""
  tls:
    - hosts:
        - test.com
      secretName: test-tls-secret
  hosts:
    - host: test.com
      http:
        paths:
          - path: /
            pathType: Prefix
