apiVersion: v2
name: agent
description: Convoy Agent Chart
type: application
version: "3.7.14"
appVersion: "v26.7.6"
maintainers:
  - name: Convoy Engineering Team
    email: engineering@getconvoy.io
    url: https://getconvoy.io
